"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { CrestLogo } from "@/components/logo";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

export default function UpdatePasswordPage() {
  const [ready, setReady] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const supabase = createSupabaseBrowserClient(); if (!supabase) { setError("Supabase is not connected yet."); return; } supabase.auth.getSession().then(({ data }) => setReady(Boolean(data.session))); const { data: listener } = supabase.auth.onAuthStateChange((event, session) => { if (event === "PASSWORD_RECOVERY" || session) setReady(true); }); return () => listener.subscription.unsubscribe(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const password = String(form.get("password")); if (password !== String(form.get("confirm"))) { setError("Your passwords do not match."); return; } const supabase = createSupabaseBrowserClient(); if (!supabase) return; const { error: updateError } = await supabase.auth.updateUser({ password }); if (updateError) setError(updateError.message); else setSaved(true); }
  return <main className="flex min-h-[calc(100vh-76px)] items-center justify-center bg-[#f0f6fb] px-5 py-16"><div className="w-full max-w-md rounded-[26px] bg-white p-7 shadow-soft sm:p-10"><CrestLogo />{saved ? <div className="mt-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#e7f4e9] text-shamrock"><Check size={26} /></div><h1 className="mt-6 text-3xl font-bold text-blue-950">Password updated</h1><p className="mt-3 text-sm text-slate-500">You can now sign in with your new password.</p><Link href="/login" className="mt-7 inline-block text-sm font-bold text-blue-900 underline underline-offset-4">Go to sign in</Link></div> : <><h1 className="mt-10 text-3xl font-bold tracking-tight text-blue-950">Choose a new password</h1><p className="mt-3 text-sm leading-6 text-slate-500">Use at least 8 characters for your club leader account.</p>{!ready && !error && <p className="mt-6 rounded-xl bg-[#fff8cf] px-4 py-3 text-xs font-semibold text-[#8b6d00]">Open this page using the link from your reset email.</p>}<form onSubmit={submit} className="mt-7 space-y-4"><input required minLength={8} type="password" name="password" placeholder="New password" className="outline-ring w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm text-slate-700 focus:border-blue-900" /><input required minLength={8} type="password" name="confirm" placeholder="Confirm new password" className="outline-ring w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm text-slate-700 focus:border-blue-900" />{error && <p className="rounded-xl bg-[#fff0e5] px-4 py-3 text-xs font-semibold text-orange">{error}</p>}<button disabled={!ready} className="flex w-full items-center justify-center rounded-xl bg-blue-900 py-4 text-sm font-bold text-white disabled:opacity-40">Update password<ArrowRight size={16} className="ml-2" /></button></form></>}</div></main>;
}
