"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, LockKeyhole } from "lucide-react";
import { CrestLogo } from "@/components/logo";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

export default function LoginPage() {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const identifier = String(form.get("identifier")); const password = String(form.get("password")); const supabase = createSupabaseBrowserClient(); if (!supabase) { window.location.href = "/admin"; return; } let email = identifier; if (!identifier.includes("@")) { const { data, error: lookupError } = await supabase.rpc("resolve_login_email", { login_username: identifier }); if (lookupError || !data) { setError("Username not found. Check your username or use your email address."); setBusy(false); return; } email = data; } const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) { setError("Those login details were not recognised."); setBusy(false); return; } window.location.href = "/admin"; }
  return <main className="grid min-h-[calc(100vh-76px)] bg-[#f0f6fb] lg:grid-cols-2"><div className="hidden bg-blue-900 p-12 lg:flex lg:flex-col lg:justify-between"><CrestLogo dark /><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-bumblebee">Club leaders hub</p><h1 className="mt-4 max-w-md text-5xl font-bold leading-tight tracking-[-.04em] text-white">The little things add up to something big.</h1><p className="serif mt-6 max-w-sm text-sm leading-7 text-white/60">Keep your club moving, your people connected, and your next great idea in motion.</p></div><p className="text-xs text-white/35">Rusinga School · Clubs & activities</p></div><div className="flex items-center justify-center px-5 py-14 sm:px-8"><div className="w-full max-w-md"><Link href="/" className="mb-12 inline-flex items-center gap-2 text-xs font-bold text-blue-900"><ArrowLeft size={14} /> Back to Rusinga Clubs</Link><div className="mb-9 lg:hidden"><CrestLogo /></div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-violet">Welcome back</p><h2 className="mt-3 text-4xl font-bold tracking-tight text-blue-950">Club leader sign in</h2><p className="mt-3 text-sm text-slate-500">Sign in with your username or email and password.</p><form onSubmit={submit} className="mt-9 space-y-5"><label className="block text-xs font-bold text-blue-950">Username or email<input required type="text" name="identifier" placeholder="e.g. clubsprefect or you@rusinga.ac.ke" className="outline-ring mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 text-sm font-normal text-slate-700 placeholder:text-slate-400 focus:border-blue-900" /></label><div><div className="flex items-center justify-between"><label className="text-xs font-bold text-blue-950" htmlFor="password">Password</label><Link href="/forgot-password" className="text-[11px] font-bold text-violet underline underline-offset-4">Forgot password?</Link></div><input required id="password" type="password" name="password" placeholder="Enter your password" className="outline-ring mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 text-sm font-normal text-slate-700 placeholder:text-slate-400 focus:border-blue-900" /></div>{error && <p className="rounded-xl bg-[#fff0e5] px-4 py-3 text-xs font-semibold text-orange">{error}</p>}<button disabled={busy} className="flex w-full items-center justify-center rounded-xl bg-blue-900 py-4 text-sm font-bold text-white transition hover:bg-blue-950 disabled:opacity-50">{busy ? "Checking your details..." : "Sign in to dashboard"}<ArrowRight size={16} className="ml-2" /></button></form><div className="mt-8 flex items-center gap-2 text-[11px] text-slate-400"><LockKeyhole size={13} /> Your club data is only accessible to authorised leaders.</div></div></div></main>;
}
