import Link from "next/link";
import { ArrowRight, Check, Sparkles } from "lucide-react";
import { ClubCard } from "@/components/club-card";
import { CrestLogo } from "@/components/logo";
import { getClubs } from "@/lib/data";
import { SCHOOL_YEAR, TERM_END, TERM_START } from "@/lib/school";

export default async function Home() {
  const clubs = await getClubs();
  const clubCount = String(clubs.length).padStart(2, "0");
  return <main>
    <section className="relative overflow-hidden bg-[#f0f6fb] px-5 pb-20 pt-16 sm:px-8 sm:pb-28 sm:pt-24 lg:px-10">
      <div className="pointer-events-none absolute inset-0 bg-hero-grid bg-[size:44px_44px] opacity-50" /><div className="pointer-events-none absolute -right-28 -top-28 h-96 w-96 rounded-full bg-[#dbe9f5] blur-3xl" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1fr_420px] lg:gap-24">
        <div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-blue-900/10 bg-white/70 px-3 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-blue-900"><Sparkles size={13} className="text-orange" /> {SCHOOL_YEAR} school year · {TERM_START}–{TERM_END}</div><h1 className="text-balance text-5xl font-extrabold leading-[1.04] tracking-[-.05em] text-blue-950 sm:text-7xl">Find your thing.<br /><span className="text-violet">Make your mark.</span></h1><p className="serif mt-7 max-w-lg text-base leading-8 text-slate-600 sm:text-lg">Rusinga is more than the classroom. Discover the people, ideas, and projects that make school yours.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="#clubs" className="rounded-full bg-blue-900 px-6 py-3.5 text-[13px] font-bold text-white shadow-lg shadow-blue-900/15 transition hover:bg-blue-950">Explore clubs <ArrowRight size={15} className="ml-2 inline" /></Link><Link href="/join" className="text-[13px] font-bold text-blue-900 underline decoration-blue-900/20 underline-offset-8 transition hover:decoration-blue-900">How joining works</Link></div></div>
        <div className="relative mx-auto w-full max-w-[390px] lg:mr-0"><div className="float relative rounded-[28px] bg-blue-900 p-7 shadow-2xl shadow-blue-900/20"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/50">Your year, your way</p><p className="mt-2 text-2xl font-bold text-white">Something for<br />every curious mind.</p></div><div className="text-4xl text-bumblebee">✦</div></div><div className="mt-8 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-white/10 px-2 py-4"><div className="text-2xl font-bold text-white">{clubCount}</div><div className="mt-1 text-[9px] uppercase tracking-wider text-white/50">clubs</div></div><div className="rounded-2xl bg-white/10 px-2 py-4"><div className="text-2xl font-bold text-white">2</div><div className="mt-1 text-[9px] uppercase tracking-wider text-white/50">choices</div></div><div className="rounded-2xl bg-white/10 px-2 py-4"><div className="text-2xl font-bold text-white">∞</div><div className="mt-1 text-[9px] uppercase tracking-wider text-white/50">ideas</div></div></div><div className="mt-6 flex items-center gap-3 rounded-2xl bg-white p-3"><div className="flex -space-x-2"><span className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-white bg-violet text-[9px] font-bold text-white">A</span><span className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-white bg-orange text-[9px] font-bold text-white">K</span><span className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-white bg-shamrock text-[9px] font-bold text-white">M</span></div><span className="text-[11px] font-semibold leading-4 text-slate-600">Your next<br /><b className="text-blue-900">chapter starts here.</b></span><Check size={16} className="ml-auto text-shamrock" /></div></div><div className="absolute -bottom-5 -left-6 rounded-2xl bg-white px-4 py-3 shadow-xl shadow-blue-900/10"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-shamrock" /><span className="text-[11px] font-bold text-blue-950">Registration is open</span></div></div></div>
      </div>
    </section>
    <section id="clubs" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-violet">Find your people</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-blue-950 sm:text-4xl">There&apos;s a place for you here.</h2></div><p className="max-w-xs text-sm leading-6 text-slate-500">Choose up to two clubs for the {SCHOOL_YEAR} school year.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{clubs.map((club) => <ClubCard key={club.id} club={club} />)}</div></section>
    <footer className="bg-blue-950 px-5 py-10 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 sm:flex-row sm:items-center"><CrestLogo dark /><div className="text-xs text-white/45">Made for curious minds at Rusinga School</div><Link href="/login" className="text-xs font-semibold text-white/70 transition hover:text-white">Club leader sign in →</Link></div></footer>
  </main>;
}
