"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { CrestLogo } from "@/components/logo";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

export default function ForgotPasswordPage() {
  const [sent, setSent] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const email = String(new FormData(event.currentTarget).get("email")); const supabase = createSupabaseBrowserClient(); if (!supabase) { setError("Supabase is not connected yet."); setBusy(false); return; } const { error: resetError } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/update-password` }); if (resetError) setError(resetError.message); else setSent(true); setBusy(false); }
  return <main className="flex min-h-[calc(100vh-76px)] items-center justify-center bg-[#f0f6fb] px-5 py-16"><div className="w-full max-w-md rounded-[26px] bg-white p-7 shadow-soft sm:p-10"><CrestLogo /><Link href="/login" className="mt-10 inline-flex items-center gap-2 text-xs font-bold text-blue-900"><ArrowLeft size={14} /> Back to sign in</Link>{sent ? <div className="mt-8"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#e7f4e9] text-shamrock"><Check size={24} /></div><h1 className="mt-6 text-3xl font-bold tracking-tight text-blue-950">Check your inbox</h1><p className="serif mt-3 text-sm leading-7 text-slate-500">If that email belongs to a club leader, Supabase has sent a password reset link.</p></div> : <><p className="mt-8 text-[11px] font-bold uppercase tracking-[.2em] text-violet">Account recovery</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-blue-950">Reset your password</h1><p className="mt-3 text-sm leading-6 text-slate-500">Enter your club leader email and we&apos;ll send you a secure reset link.</p><form onSubmit={submit} className="mt-7 space-y-4"><input required type="email" name="email" placeholder="you@rusinga.ac.ke" className="outline-ring w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm text-slate-700 focus:border-blue-900" />{error && <p className="rounded-xl bg-[#fff0e5] px-4 py-3 text-xs font-semibold text-orange">{error}</p>}<button disabled={busy} className="flex w-full items-center justify-center rounded-xl bg-blue-900 py-4 text-sm font-bold text-white disabled:opacity-50">{busy ? "Sending link..." : "Send reset link"}<ArrowRight size={16} className="ml-2" /></button></form></>}</div></main>;
}
